[package]
name = "http-rs_plus"
version = "0.8.9"
edition = "2021"
authors = ["RSGhostTech","momo"]
description = "A http library for server and client"
rust-version = "1.60.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]